// Copyright 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package instances

import (
	"errors"
	"os"
	"path/filepath"
)

var (
	// ErrInstanceNotFound is returned when an instance is not found
	ErrInstanceNotFound = errors.New("instance not found")
	// ErrInstanceExists is returned when trying to add a duplicate instance
	ErrInstanceExists = errors.New("instance already exists")
	// ErrInvalidPath is returned when a path is invalid or empty
	ErrInvalidPath = errors.New("invalid path")
)

// InstancePaths represents the paths in an instance
type InstancePaths struct {
	// Source is the directory containing source files (absolute path)
	Source string `json:"source"`
	// Configuration is the directory containing workspace configuration (absolute path)
	Configuration string `json:"configuration"`
}

// InstanceData represents the serializable data of an instance
type InstanceData struct {
	// ID is the unique identifier for the instance
	ID string `json:"id"`
	// Paths contains the source and configuration directories
	Paths InstancePaths `json:"paths"`
}

// Instance represents a workspace instance with source and configuration directories.
// Each instance is uniquely identified by its ID.
// Instances must be created using NewInstance to ensure proper validation and path normalization.
type Instance interface {
	// GetID returns the unique identifier for the instance.
	GetID() string
	// GetSourceDir returns the source directory.
	// The path is always absolute.
	GetSourceDir() string
	// GetConfigDir returns the configuration directory.
	// The path is always absolute.
	GetConfigDir() string
	// IsAccessible checks if both source and config directories are accessible
	IsAccessible() bool
	// Dump returns the serializable data of the instance
	Dump() InstanceData
}

// instance is the internal implementation of Instance
type instance struct {
	// ID is the unique identifier for the instance
	ID string
	// SourceDir is the directory containing source files.
	// This is always stored as an absolute path.
	SourceDir string
	// ConfigDir is the directory containing workspace configuration.
	// This is always stored as an absolute path.
	ConfigDir string
}

// Compile-time check to ensure instance implements Instance interface
var _ Instance = (*instance)(nil)

// GetID returns the unique identifier for the instance
func (i *instance) GetID() string {
	return i.ID
}

// GetSourceDir returns the source directory
func (i *instance) GetSourceDir() string {
	return i.SourceDir
}

// GetConfigDir returns the configuration directory
func (i *instance) GetConfigDir() string {
	return i.ConfigDir
}

// IsAccessible checks if both source and config directories are accessible
func (i *instance) IsAccessible() bool {
	if !isDirAccessible(i.SourceDir) {
		return false
	}
	if !isDirAccessible(i.ConfigDir) {
		return false
	}
	return true
}

// Dump returns the serializable data of the instance
func (i *instance) Dump() InstanceData {
	return InstanceData{
		ID: i.ID,
		Paths: InstancePaths{
			Source:        i.SourceDir,
			Configuration: i.ConfigDir,
		},
	}
}

// NewInstance creates a new Instance with validated and normalized paths.
// Both sourceDir and configDir are converted to absolute paths.
// The ID is empty and will be generated by the Manager when the instance is added to storage.
func NewInstance(sourceDir, configDir string) (Instance, error) {
	if sourceDir == "" {
		return nil, ErrInvalidPath
	}
	if configDir == "" {
		return nil, ErrInvalidPath
	}

	// Convert to absolute paths
	absSourceDir, err := filepath.Abs(sourceDir)
	if err != nil {
		return nil, err
	}

	absConfigDir, err := filepath.Abs(configDir)
	if err != nil {
		return nil, err
	}

	return &instance{
		ID:        "", // ID will be set by Manager when added
		SourceDir: absSourceDir,
		ConfigDir: absConfigDir,
	}, nil
}

// NewInstanceFromData creates a new Instance from InstanceData.
// The paths in InstanceData are assumed to be already validated and absolute.
func NewInstanceFromData(data InstanceData) (Instance, error) {
	if data.ID == "" {
		return nil, errors.New("instance ID cannot be empty")
	}
	if data.Paths.Source == "" {
		return nil, ErrInvalidPath
	}
	if data.Paths.Configuration == "" {
		return nil, ErrInvalidPath
	}

	return &instance{
		ID:        data.ID,
		SourceDir: data.Paths.Source,
		ConfigDir: data.Paths.Configuration,
	}, nil
}

// isDirAccessible checks if a directory exists and is accessible
func isDirAccessible(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}
	return info.IsDir()
}
